app {
  http {
    host = "0.0.0.0"
    host = ${?HTTP_HOST}
    port = 8081
    port = ${?HTTP_PORT}
    timeout = 40 seconds
    timeout = ${?HTTP_TIMEOUT}
  }
  one-frame {
    base-uri = "http://localhost:8080"
    base-uri = ${?ONE_FRAME_BASE_URI}
    token = "10dc303535874aeccc86a8251e6992f5"
    token = ${?ONE_FRAME_TOKEN}
    refresh-interval = 4 minutes
    refresh-interval = ${?ONE_FRAME_REFRESH_INTERVAL}
    max-rate-age = 5 minutes
    max-rate-age = ${?ONE_FRAME_MAX_RATE_AGE}
  }
  redis {
    uri = "redis://localhost:6379"
    uri = ${?REDIS_URI}
    key-prefix = "forex:rates"
    key-prefix = ${?REDIS_KEY_PREFIX}
    refresh-lock-ttl = 30 seconds
    refresh-lock-ttl = ${?REDIS_REFRESH_LOCK_TTL}
  }
}
